changelog:
  exclude:
    labels:
      - ignore-for-release
      - chore
    authors:
      - dependabot
      - renovate
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other changes
      labels:
        - '*'